# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box="ubuntu/bionic64"
    web.vm.hostname = "web.bt.local"
    web.vm.network "private_network", ip: "192.168.81.107"
    web.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    # web.vm.synced_folder "vagrant/web/", "/vagrant/"
    web.vm.provision "shell", path: "../ubuntu/provision.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box="ubuntu/bionic64"
    db.vm.hostname = "db.bt.local"
    db.vm.network "private_network", ip: "192.168.81.108"
    db.vm.synced_folder "vagrant/db/", "/vagrant/"
    # db.vm.provision "shell", path: "../ubuntu/provision.sh"
  end

end
